### ISSUE TITLE
KERI based Universal DID Method  did:un  did:uni

### ISSUE THREAD

**Issue by SmithSamuelM** [decentralized-identity/keri#12]
Community feedback

did:un 
vs
did:uni

**Comment by bumblefudge** [comment]
I prefer "un" because when people say "the DID:un method" it will sound like they're saying "the DID un-method" and "unmethod"/"unmethoding" is a pithy name for counterveiling force that prevents DID methods from becoming walled gardens 😎

**Comment by dhh1128** [comment]
How about just `did:u`?

**Comment by mitfik** [comment]
:+1:  did:un

**Comment by chunningham** [comment]
also voting for `did:un`

**Comment by tmarkovski** [comment]
`did:un`, but also like Daniel's proposal `did:u`
