### ISSUE TITLE
Normative reference issue in spec

### ISSUE THREAD

**Issue by nembal** [decentralized-identity/keri#138]
Dear KERI community,

I would like to remind everyone that normative references should only point to IPR protected work items. 
As I read through the Spec I found that the first normative reference is a personal repository on github. 
Either get the owner to donate the repository to DIF or reconsider using it as a normative reference as this way the spec will not be approvable by DIF. 

Thanks,

**Comment by pfeairheller** [comment]
Thank you for catching that.  The use of the white paper as a normative reference was caught during the first review.  I _thought_ fixed them on by pointing them to the appropriate KID but missed this one.
