### ISSUE TITLE
ECDSA secp256k1 derivation data lengths

### ISSUE THREAD

**Issue by chunningham** [decentralized-identity/keri#26]
Table 14.2 in the paper describes one-char derivation codes (for 32-byte inputs) and includes the secp256k1 public key derivation procedures. These public keys are actually 33 bytes in length (or, rather annoyingly, 257 bits exactly), so they'll actually be a 4 char code. Alternatively, they could be digested to 32 bytes, but this seems unnecessary. Tentatively I'd propose they be labelled A and B in the yet-to-have-rows 4 char table.

**Comment by SmithSamuelM** [comment]
See  https://github.com/decentralized-identity/keri/blob/master/kids/KERIDerivationCode.xlsx.zip  which contains 4 character table.  This is temporary until we can generate markdown version. The excel version includes 33 byte public keys in 4 character table.
