### ISSUE TITLE
implementation: where and when do we start?

### ISSUE THREAD

**Issue by llorllale** [decentralized-identity/keri#3]
In [this](https://hackmd.io/orhyiJkLT721v4PCPkvQiA) doc we listed a few languages and put some names there:

```
Languages: Python, Javascript (nodejs), Rust, Python +rust keripy, kerijs, keriox,
Discussion:
    Sam: Py
    Spherity (hi!): nodeJS
    Rust? JOLOCOM ftw (or at least Charles) “KeriOX”
```

@SmithSamuelM suggests we convene at the biweekly Identifier & Discovery group meetings hosted by DIF.

I'm a newbie at both Python and Rust (but experienced at Java & Golang) and I wish to get involved. Where do I track this work so I can get involved? Do I need to wait for the next DIF ID+Discovery call?

**Comment by SmithSamuelM** [comment]
DIF Identifiers and Discovery Biweekly
Next one May 11 at 11 am PDT


<br><b>Meeting page and agenda: </b><a href="https://docs.google.com/document/d/1gV99R7G2bUlRerxznyd0ucwWPfc1v2F2gQVaTawIPYI/">https://docs.google.com/document/d/1gV99R7G2bUlRerxznyd0ucwWPfc1v2F2gQVaTawIPYI/</a><br><br>-------------------------<br><br>&nbsp;Identifiers and Discovery WG Bi-weekly meeting<br>URL: <a href="https://zoom.us/j/801382311">https://zoom.us/j/801382311</a><br><br><br>Meeting ID: 801 382 311<br><br><br>Mobile:<br>&nbsp;&nbsp;+19294362866,,801382311# <br>&nbsp;&nbsp;+16699006833,,801382311# <br><br>Telephone:<br>&nbsp;&nbsp;+1 929 436 2866<br>&nbsp;&nbsp;+1 669 900 6833 <br><br>International numbers available: <a href="https://zoom.us/u/bb7kqZ56X">https://zoom.us/u/bb7kqZ56X</a>

**Comment by peacekeeper** [comment]
_(correct formatting:)_

DIF Identifiers and Discovery Biweekly
Next one May 11 at 11 am PDT

Meeting page and agenda: https://docs.google.com/document/d/1gV99R7G2bUlRerxznyd0ucwWPfc1v2F2gQVaTawIPYI/

Bi-weekly meeting for the Identifiers and Discovery WG

URL: https://zoom.us/j/801382311
Meeting ID: 801 382 311

Mobile:
  +19294362866,,801382311#
  +16699006833,,801382311#
Telephone:
  +1 929 436 2866
  +1 669 900 6833

International numbers available: https://zoom.us/u/bb7kqZ56X

**Comment by peacekeeper** [comment]
The DIF **#wg-id** Slack channel can also be used for discussing this: https://difdn.slack.com/archives/C4WED8JSH

**Comment by SmithSamuelM** [comment]
See also implementation.md in this repo
