### ISSUE TITLE
Inception Event Key Representations is defined in which RFC?

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/keri#32]
```
{
  "vs"   : "KERI10JSON00011c_",
  "id"   : "AaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM",  // qualified Base64
  "sn"   : "0",  // lowercase hex string no leading zeros
  "ilk"  : "icp",
  "sith" : "1",  // lowercase hex string no leading zeros or list
  "keys" : ["AaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM"],  // list of qual Base64
  "next" : "DZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM",  // qualified Base64
  "toad" : "1",  // lowercase hex string no leading zeros
  "wits" : [],  // list of qualified Base64
  "data" : [],  // list of config ordered mappings
  "sigs" : []  // optional list of or single lowercase hex string(s) no leading zeros
}
```

`AaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM`.... what is this, where is it defined (which RFC?)

Ideally, we can start with some known entropy, generate a well known key format (like base58btc multicodec / JWK) and then show how to convert that to a KERI key representation...

I am strongly opposed to inventing a new base64 based key representation along with KERI.... if we do that, we better make it configurable accross the board.

**Comment by OR13** [comment]
Similar question for `DZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM`.... not enough information in:

`next = next digest of ensuing threshold and signers (icp, rot, dip, drt)`

to implement.

**Comment by SmithSamuelM** [comment]
Currently implementation will be difficult without first reading the white paper.  https://github.com/SmithSamuelM/Papers/blob/master/whitepapers/KERI_WP_2.x.web.pdf

We are definitely planning to move the relevant sections from the WP into KIDs.  Frankly we have a target of getting a reference implementation working for IIW this fall, and will until then prioritize that over extensive documentation.
