### ISSUE TITLE
Digest Agility  Adding back in sn to event seal

### ISSUE THREAD

**Issue by SmithSamuelM** [decentralized-identity/keri#74]
An earlier version of the protocol included the "sn" sequence number field in the event seal as follows:
JSON encoding for example.

```json
{
   "pre": "Ebcdefgh...",
   "sn": "2",
  "dig": "E38c4rjto..."
}
```

This was changed to the following:
```json
{
   "pre": "Ebcdefgh...",
  "dig": "E38c4rjto..."
}
```

One reason for the change is that the digest of the event is unique and can be used to look up the associated event in the KEL database merely by digest. This assumes however that the digest type used to index the event in the database is the same as the digest type in the seal. This is not a valid assumption in general unless the digest type for events entered in the databased and event chaining and event seals is fixed for a given version of the KERI protocol. 

In addition there is ambiguity as to which digest to use when one gets an inception event as the inception event itself does not have a digest of the preceding event so we can't get a hint from the inception event itself.  So anytime we store an event in the database by digest we have to assume a digest type.  Any other digest of a different type requires recomputing that new type digest on the event.

The decision is between A and B:

A)
Add back in the sn to the event seal. This means that lookup for the event referenced by the seal happens by sn not digest. The lookup by sn then returns a digest that is then used to lookup the actual event. The reason for this two step index is that with a recovery the KEL maybe forked and multiple events will have the same sn.  If the digest type used to index the event into the database is different from the seal digest type then a new digest of the event using the seal type must be computed to determine if the seal digest is indeed pointing to the correct event. A complication would be if the event referenced by the seal is not a rotation (establishment)event. In this case multiple recoveries may have occurred so that the sn appears in multiple forks. Fortunately for transferable receipts the seal may only referent to a rotation event which may not be recovered and appear in multiple forks. Likewise a delegation seal may only refer to an establishment event which may not be recovered and appear multiple times. Thus the latest event at that sn must be the event or else the seal is invalid.  This means that we may only use event seals to refer to establishment events which may not be forked. Interactions events may be forked and the same sn may appear multiple times. We may then have to search all the instances to find the match. I believe that in all cases of prior event match that only the latest version of an event with the same sn is useful for matching previous event digest on a new event. So would only have to check compare against the last event version not all.

Likewise when receiving a new event and checking the previous event digest with the key state, one would have to first compare digest types and if they do not match recompute the key event state digest with the type of the new event's prior digest to compare if the digests are for the same event.

In general anytime a digest comparison is made, the comparison must first compare the types of the digests and if different then recompute one in order to make a comparison between digests of the same type to see if they refer to the same data.

 B)
The alternative is to standardize on one digest type for a given version of the protocol. Then nothing changes.  The disadvantage is that it might be a problem for some implementations (but any implementation that doesn't support any digest type already has an interoperability problem), but this may make it worse in the sense that whatever digest we pick must be the best one. This would not affect digests for external data seals or for the nxt keys, but only the event seal and any digest comparisons of event digests.  The advantage is  we wold not ever have to do the extra  digest checks and computations  nor incur the cost of adding sn to the event seal.  We can assume that all events and event seals to events of a given type share the same digest type for a given version of the protocol. We still would have digest agility across versions but not by event.

C) Add an "own event digest type code" element to each event to indicate how to hash that event and reference it in general.  This has the disadvantage of adding a new element to every event but does allow agility without incurring the type comparison and recompilation of digests when types don't match. So its more bandwidth for all events vs more computation for some events. All entries in databases, all seals of an event would use the hash type specified by the Own Digest Type Code element for that event. It would not require adding the "sn" field back into the event seal.  

Please provide feedback as to concerns etc. preferences of which way to go to repair it.

**Comment by OR13** [comment]
this is the same issue @csuwildcat raised related to did core... essentially, a need to upgrade identifiers.

its also imo best solved by https://github.com/multiformats/multicodec

If I could force KERI to just use multicodec, I would :)

**Comment by SmithSamuelM** [comment]
No it would not be fixed by multi-codec.  It does not solve the problem.

**Comment by SmithSamuelM** [comment]
@OR13  ;) you would also force KERI to use JSON-LD JWT and a bunch of stuff too verbose for event streaming performant applications ;) If you could

**Comment by chunningham** [comment]
I would opt for option A, it also makes finding the receipted event much quicker and simplifies the Seal type by essentially removing one of the variants. Option B will limit the ability of some environment-constrained use cases to use the digests available to them and would basically say "always use BLAKE3". Option A also allows a storage mechanism to choose a reasonable default digest for CAS while still enabling fast lookup (find by sn and check digest matches) without worrying about changing digest type and re-storing data when a controller changes their choice of digest.

**Comment by chunningham** [comment]
and yeah essentially all the benefits to KERI of `multicodec` are already provided by the derivation/prefix sub-spec in a way that IMO is quite neat. If `multicodec` was used it would have to be a specified subset anyway, almost like a table of accepted values with prepended codes that indicate the type :laughing:.

**Comment by SmithSamuelM** [comment]
>I would opt for option A, it also makes finding the receipted event much quicker and simplifies the Seal type by essentially removing one of the variants. Option B will limit the ability of some environment-constrained use cases to use the digests available to them and would basically say "always use BLAKE3". Option A also allows a storage mechanism to choose a reasonable default digest for CAS while still enabling fast lookup (find by sn and check digest matches) without worrying about changing digest type and re-storing data when a controller changes their choice of digest.


I am not disagreeing with option A. I just want to be clear that I understand your reasons.  

- finding receipted event much quicker.  
Not necessarily lookup by digest may be just as fast as lookup by sn

- simplifies Seal type by removing a variant
No the location seal is still different than the event seal. It complicates the event seal by adding one field.

 -always use BLAKE3
Yes this may be problematic for some

- reasonable default digest without reindexing database if digest different

Yes Most of the time if the default is the same then its effectively acts like B but with agility when it needs to be different


So I don't see any speed advantages of A over B but I do see the agility advantages

I am tempted by agility but I always have to temper that by recognizing the simplicity of less agility. How much agility is just the right amount.

**Comment by sethjback** [comment]
I would vote for option A as well (with a question/caveat below): it seems like the storage/retrieval logic is separate from the protocol functionality, and in the latter digest agility seems important enough to handle any potential added complexity on the former. 

The caveat: for the `nxt` field we require the same derivation for all prefixes. While the reasons are different, is there some precedence for another option: having the seal digest derivation match the digest derivation of the event? (although, as you point out, this would not work on inception events, but then one could argue there would be no real issues finding `sn` 0).

My questions: I am not sure I follow the issue of a forked `KEL`. As I understand event seals are to anchor one event to another in the `KEL`. If the event providing the seal is anchoring to a "forked" event, is that forked event invalid? Presumably you would want to invalidate the linking event seal, correct?

During a recovery, are you envisioning keeping the invalid `KEL` branch? If not, then wouldn't the digest that the seal is linked to go away?

Am I thinking about this correctly: shouldn't there only be a single valid event for any given `sn`?

**Comment by stevetodd** [comment]
> Am I thinking about this correctly: shouldn't there only be a single valid event for any given sn?

There's only one valid event, but in the case of key compromise or duplicity, there could be multiple non-establishment events at the same sn simultaneously. This only gets resolved after a rotation event, which then will tell you which ones are valid and which ones are not. For establishment events, there is only one valid event for a given sn.

**Comment by stevetodd** [comment]
> During a recovery, are you envisioning keeping the invalid KEL branch? If not, then wouldn't the digest that the seal is linked to go away?

You want to keep the invalid events as a record of duplicitous behavior.

**Comment by sethjback** [comment]
> There's only one valid event, but in the case of key compromise or duplicity, there could be multiple non-establishment events at the same sn simultaneously. This only gets resolved after a rotation event, which then will tell you which ones are valid and which ones are not. For establishment events, there is only one valid event for a given sn.

Yep. This is a timing issue though, correct? If you have an event seal coming in **after** the recover has taken place, you don't want it to validate. If it comes in before, the issues is moot, right?

> You want to keep the invalid events as a record of duplicitous behavior.

Yes, but going forward (after the recovery), practically you would need to operate as if the "fork" didn't exist and process events as normal (using the recovered branch).

This might be an interesting question for the API discussion: should there be ways to query for invalidated forks in the event log?

**Comment by stevetodd** [comment]
My thoughts on Options:
* Algorithm agility is good and I think we want to keep it, so not (B)
* Like @sethjback, I think that the storage concern is not a protocol concern, so I'd be less inclined to do (C).
* This leaves me with (A).

 I'd probably store the events with a generated ID, with a collection of prefix:sn:digest->ID mappings. There's also no guarantee that the entity creating the seal will use the same digest algorithm as the controller—they may choose another for whatever reason.

**Comment by SmithSamuelM** [comment]
It seems that supporting agility A)  is preferable.  I am not sure everyone recognizes that there is likely additional computation with A)  but there are ways to manage it so that its limited such as by reindexing events to match the digest used in the subsequent event assuming that the creator of the key event stream is not changing digest types very often.

So I am happy with A)   So unless anyone objects lets go with A)

**Comment by chunningham** [comment]
@stevetodd's comment about the receipt creator not using the same digest I think is the crux of the issue (for me annyway), without an `sn` the processor would have to compare digests for potentially every event in the KEL. in practice this wont be too crazy unless KELs get very (10000's probably) long, but it feels unnecessary

**Comment by SmithSamuelM** [comment]
One thing to be aware of is that in order to replay events in the correct order for a given identifier a table or index is needed that allows one to iterate through the events by sn. Including the digest in such an index such as prefix:sn:digest would not be iterable by sn given recovery forks.   The python implementation has two tables one indexed by prefix:sn  -> digest and then another by prefix:digest -> event   

Also anther thing to be aware of is that if one wants to support the GDPR right of erasure one needs to be able to track down and remove all events belonging to a prefix but not some other prefix.

**Comment by SmithSamuelM** [comment]
The KeriPy supports this with this pull request>  https://github.com/decentralized-identity/keripy/pull/63

**Comment by bumblefudge** [comment]
Merged, review period closed.
