### ISSUE TITLE
Proposed Key Event State Messages

### ISSUE THREAD

**Issue by SmithSamuelM** [decentralized-identity/keri#77]
Key Event State or Key State Messages

There are two forms. One when signed by entities with non-transferable identifiers such as witnesses and watchers and the other with signed by entities with transferable identifiers such as controllers and validators. The transferable form includes an event seal of the  establishment event that provides the keys used to sign the event.

This proposal uses the two character codes in the proposed new code see issue #75. But can be changed to whatever we decide.

Message Kind (Ilk)

Non-transferable signer:
mt = "ksn"

Transferable signer:
mt = "kst"

Message for non-transferable signer is shown below. A non-transferable sourced key state message has attached a couplet of signer identifier and signature. This is the same format for signatures as the non-transferable sourced receipt message.

```json

{
  "vn"   : "1.0",   // Version Number major.minor  only string not full version string
  "ip"  : "EaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM",  // identifier prefix qualified Base64
  "sn"   : "0",  // lowercase hex string no leading zeros
  "mt"  : "ksn",  // message type of this message
  "et"   : "rot",  // event type of latest event in KEL
  "dg" :  "EAoTNZH3ULvaU6JR2nmwyYAfSVPzhzZ-i0d8JZS6b5CM",  // qualified Base64
  "st" : "1",  // lowercase hex string no leading zeros or list
  "kl" : ["DaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM"],  // list of qual Base64
  "nk"  : "EZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM",  // qualified Base64
  "wt" : "1",  // lowercase hex string no leading zeros
  "wl" : ["DnmwyYAfSVPzhzS6b5CMZ-i0d8JZAoTNZH3ULvaU6JR2"],  // list of qualified Base64
  "eo" : "true",  // list of config ordered mappings
  "ee" : 
         {
           "sn":  "1",
           "dg":  "EAoTNZH3ULvaU6JR2nmwyYAfSVPzhzZ-i0d8JZS6b5CM"
          }
  "dd": "false",
  "dp": ""
}

-AABB8KY1sKmgyjAiUDdUBPNPyrSz_ad_Qf9yzh'
                                b'DNZlEKiMc0Bi6u-ogCjhGeXMUV0Vls9RbefJ-W_daYc6aBVPY5fqMsBYhkl47Trh'
                                b'bpescYp-yBcfkEEKUQHEpZhoXgzw3IeDQ'
```

Message for transferable signer is shown below. A transferable sourced key state message includes an event seal for the event in the signer's KEL that provided the keys used to sign.  Attached are indexed signatures using the keys listed in that event indicated by the seal. This is the same format for signatures as the transferable sourced receipt message.

```json

{
  "vn"   : "1.0",   // Version Number major.minor  only string not full version string
  "ip"  : "EaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM",  // identifier prefix qualified Base64
  "sn"   : "0",  // lowercase hex string no leading zeros
  "mt"  : "kst",  // message type of this message
  "et"   : "rot",  // event type of latest event in KEL
  "dg" :  "EAoTNZH3ULvaU6JR2nmwyYAfSVPzhzZ-i0d8JZS6b5CM",  // qualified Base64
  "st" : "1",  // lowercase hex string no leading zeros or list
  "kl" : ["DaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM"],  // list of qual Base64
  "nk"  : "EZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM",  // qualified Base64
  "wt" : "1",  // lowercase hex string no leading zeros
  "wl" : ["DnmwyYAfSVPzhzS6b5CMZ-i0d8JZAoTNZH3ULvaU6JR2"],  // list of qualified Base64
  "eo" : "true",  // list of config ordered mappings
  "ee" : 
         {
           "sn":  "1",
           "dg":  "EAoTNZH3ULvaU6JR2nmwyYAfSVPzhzZ-i0d8JZS6b5CM"
          }
  "dd": "false",
  "dp": "",
  "es":
         {
             "ip":  "EJZAoTNZH3ULvYAfSVPzhzS6b5aU6JR2nmwyZ-i0d8CM",
              "sn":  "1",
              "dg":  "EULvaU6JR2nmwyAoTNZH3YAfSVPzhzZ-i0d8JZS6b5CM"
        }
}

-AAB
AAwyZ-i0d8JZaU6JR2nAoTNZH3ULvYAfSVPzhzS6b5CM0BIJB4pny2YpuB3m6-pgyl4cU65RRCASb9qBNXUerVs4IDYnai29AXcPQJtudLPfzfvehicA7LrswWBPmNlNQK9g
```

**Comment by stevetodd** [comment]
In regards to the comment in [#75](https://github.com/decentralized-identity/keri/issues/75#issuecomment-741963251), I had some questions about this first. In what cases would I come into possession of a Key Event State Message? Is this in response to a request to get an identifier state from a verifier? The part that kind of trips me up is having both a message type and an event type in this message. I'm also having a hard time understanding what eo, ee, and es are for.

**Comment by SmithSamuelM** [comment]
Key state is currently maintained to help validate new events relative to the key state. So for example the logic to determine if a new event is valid is a function of the last event.  I put everything that is in the key state in the message as a first pass. It may be that we don’t need everything in the actual key state to be in the key state message. Maybe only some things.  But that is a different topic. So assuming that we need everything how would it look?

In the specific case of the event type, for example, the event type of the last event is used to determine if the new event is valid. for example a rotation event cannot be recovered but an interaction event can which means if the sn are the same and the last event is interaction then a new rotation event is allowed as a recovery.

Likewise everthing in the key state is used in some validation logic.

The EstOnly  “do” is the value of a configuration trait that says only establishment events are allowed for this prefix.

Likewise  EE is LastEstablishmentEvent which is used in recovery.  

Part of the confusion is that I used the shorted two character labels from the original table above but if you look at the table above it defines the longer meaning.

**Comment by chunningham** [comment]
if Identifier state messages never actually appear in the core KERI protocol (afaik) then should they just use a more human readable set of labels as they wont have the same size needs as events (per identifier vs. per event)?

Additionally, is the intent to provide a "trusted snapshot" that can have events applied to it? if so then some additional info might have to be included. For example, instead of a digest of the previous event, it would have to contain the full bytes so that digest agility can be possible (if the next event arrives and is using a different digest alg it will not match), perhaps that's not the idea though

**Comment by stevetodd** [comment]
> if Identifier state messages never actually appear in the core KERI protocol (afaik) then should they just use a more human readable set of labels as they wont have the same size needs as events (per identifier vs. per event)?

I agree with this sentiment too. Said a different way, compact labels I think are fine for communications among KERI nodes, but where we interface with upper layers in the stack, we may want more verbose labels. My reasoning is that the compact labels will be used among KERI nodes whereas the state messages will be more likely consumed by applications built a layer above. 

For example, an application in a browser might request the state from a trusted validator and just use the parsed JSON directly rather than utilizing a KERI library. Ergonomically, the compact labels would be a pain for readability in the application's code. 

As an aside, in this use case, developers might [appreciate having the keys sent in JWK and SPKI formats](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey).

**Comment by SmithSamuelM** [comment]
The bare tcp udp transports still benefit from the compact labels. So I support having those nonetheless. But we could define in addition, different more verbose versions of these message formats for APIs used in a different layer.   

So yes I agree that a more verbose version of Key State and other messages that may be used in an HTTP Rest interface could be verbose.  I suggest that the default is to use the KERI derivation codes but support for JWT as an option would be fine with me.

However backend protocols in event streaming applications and lower level internet infrastructure benefits from a compact version of the messages like key state. So its not instead of but in addition too.

**Comment by SmithSamuelM** [comment]
@charles

KeyState isn't meant to be a cache but a polled or push notification message of the latest key state so one knows what needs to be gotten to update ones own copy of the KEL for that identifier prefix.  the digest field in any notification is obviously one of the drawbacks of digest agility because one has to get a copy of the event to know if the key state digest agrees.  But one can't know if the key state is valid unless on gets a copy of the event itself anyway.

**Comment by chunningham** [comment]
makes sense actually for constrained environments, did not consider that, and yeah a transform from basic prefix -> JWK is very straightforward (we are doing so, can publish as a separate crate soon) so I would agree in advocating against explicitly including JWK or similar in any part of the spec, it can be very easily layered on top. all in all the state message also provides a great way to define state => DID Doc. Can I suggest we also add fields for the delegator (optional) and delegates (if not already present, I have to catch up with #75)? The event seals might include delegate prefixes but I's not clear that that's what the seals are for

**Comment by SmithSamuelM** [comment]
@chunningham   The Key State message includes the delegator in the "di" labeled element. If non empty then its a delegated identifier.

Delegates are not maintained in the key state currently. there is no validation logic for key state of delegator that requires knowledge of the list of delegates. Only the delegate's validation logic requires knowledge of the delegator.

But management APIs could include and endpoint that provides a list of delegates, Indeed in general the anchors (seals) needs a management API for lots of reasons not the least of which is to track verifiable credential issuance/revocation anchors.

**Comment by bumblefudge** [comment]
Conversation moved to #75
