### ISSUE TITLE
Sidetree / DID Peer Interop

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/keri#79]
For a while now, I have had a set of tests that look sorta like this:

1. Keri Inception Event
2. Serialization for Sidetree
3. Serialization for DID Peer
5. Keri Recovery Event
6. Serialization for Sidetree
7. Serialization for DID Peer

Today, Im pretty sure that all these things would look really different... but in a year or 2... they might look more similar...

And since this is a RUST repo.... Let me be the first to ask for a WASM module that we an get binding for so that it runs in web browsers / nodejs / goland / python / java / etc...

**Comment by bumblefudge** [comment]
@OR13 could we get more detail on what you're asking? Should we revisit when Sidetree ships its spec so we have a more definitive picture of what interop would entail? Joint session at DIF F2F?

**Comment by OR13** [comment]
@bumblefudge afaik this ship sailed when keri decided to define its own even format... I don't think KERI shares any commonality with sidetree or did peer, and its no longer possible to align them, so while you can start with the same key material, doing similar operations will very quickly result in totally different event structures.

I don't see a way for KERI events to be used by anything but KERI for now, certainly not sidetree.

In the future did peer might use KERI events directly, but then did peer would not be sidetree compatible...

In order to share code / we would need shared building blocks.

sidetree is built on JWS / JWK.

keri is inventing its own key representation and signature format.

these are the lowest level building blocks, so them being different will prevent a lot of potential code reuse.

the upside is that KERI could be much better than things built on JOSE.... the down side is KERI won't be possible to implement with off the shelf JOSE crypto.

Having spent a lot of time with linked data, it looks like KERI is setup to feel all the same kind of pain, regarding reinventing the wheel instead of starting with compatibility with JOSE.

There was also a potential for KERI to align with Ceramic / IPFS / IPLD, but that door closed when the KERI WG decided to reinvent multicodec.

I predict a few years from now we will have:

A. JOSE / JWS / JWK / jose based DIDs
B. Multicodec / IPFS / IPLD / DAG_CBOR / JWS / JWK / ipld based DIDs
C. Linked Data / JSON-LD / CBOR-LD / linked data based DIDs
D. KERI / KERI keys / KERI signatures / keri event log based DIDs

There will be some overlap, for example KERI based DID Documents will likely support JWKs if they want to be useful with any legacy system, but internally KERI will use a different key representation... similarly sidetree based dids will likely support linked data proofs but will only rely on JWS / JWK for internal operations.

as far as I know, the KERI design has specifically chosen not to build on JOSE, IPLD. or JSON-LD / CBOR-LD... so there won't be any opportunity for interop with KERI below the DID Document layer.... which is true of many other systems, including Ethereum , Bitcoin, Hyperledger based DIDs... many of which don't share event log interop.

Imo, if KERI used IPLD / JSON-LD / CBOR-LD it would be better... because not using them means reinventing the parts of them that are needed... which comes with the potential for better performance at the cost of inventing a faster wheel, and failing to pull developers / tooling from those established communities. 

However I can understand the desire to control the entire stack, and not use anyone else's tooling.

From an engineering management and interop perspective, I would have decided to break compatibility after the whole system was built and working, and only in the areas where JWS / JWK or IPLD performance, documentation or library support was so bad it was justified.

As is I think this issue can be closed, and we should target interop between KERI and Sidetree at the DID Core and VC Data Model layer.

**Comment by SmithSamuelM** [comment]
@OR13 I agree that the DID and VC layers are the appopriate layers for inteop. The performance/security goals of KERI drive its design which makes incompatible with LD tooling.
