### ISSUE TITLE
Tracking kid0004 update across implementations

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/keri#90]
DFS-serialization for serialized extracted data set creation posed a malleability vulnerability when weighted sig thresholds are introduced (as explained in this [PR](https://github.com/decentralized-identity/keripy/pull/66) in keripy). To maintain interop, this must be updated. The new process is as follows:

1. collect inception data into an inception event with a dummy identifier prefix which is just # repeated to make correct length for chosen derivation code get correct version/length string from icp event
2. set verstion/length string 
3. serialize 
4. use serialization as input to prefix derivation 
5. set icp identifier prefix to derived prefix

@chunningham @Sethi.Shivam please comment on this thread when OX and JS are PRd or merged to match

**Comment by chunningham** [comment]
fully implemented
